AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  litepedia

  TODO

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

    Tracing: Active
Resources:
  Handler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handler/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          SEARCH_CACHE_TABLE: !Ref DynamoDBSearchCache
          OPENAI_API_KEY_PARAM_NAME: !Ref OpenApiKey
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBSearchCache
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDBSearchCache
        - SSMParameterReadPolicy:
            ParameterName: !Ref OpenApiKey
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
  DynamoDBSearchCache:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-search-cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: search
          AttributeType: S
      KeySchema:
        - AttributeName: search
          KeyType: HASH
  OpenApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      # After deployment, this needed updating to a secure string (can't do this in CloudFormation)
      # https://blog.rowanudell.com/managing-secure-string-parameters-in-cloudformation/
      Name: /litepedia/openai_api_key
      Description: The API key for communicating with OpenAI
      Type: String
      Value: temp

Outputs:
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Handler:
    Description: Handler Lambda Function ARN
    Value: !GetAtt Handler.Arn
  HandlerIamRole:
    Description: Implicit IAM Role created for Handler function
    Value: !GetAtt HandlerRole.Arn
  FunctionUrlEndpoint:
    Description: "Handler URL Endpoint"
    Value:
      Fn::GetAtt: HandlerUrl.FunctionUrl
  DynamoDBSearchCache:
    Description: "DynamoDBSearchCache"
    Value: !GetAtt DynamoDBSearchCache.Arn
